// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz77hiUX4-pFfTMwX9lxCpaGJ9iGbOclI',
    appId: '1:350442385764:web:d4384ea4b6c5329ae18a71',
    messagingSenderId: '350442385764',
    projectId: 'flutter-project-una',
    authDomain: 'flutter-project-una.firebaseapp.com',
    storageBucket: 'flutter-project-una.firebasestorage.app',
    measurementId: 'G-9KMEW5Z0S1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIdyChPYjCtfJeZ4fUdbZCMpgJekQkYWk',
    appId: '1:350442385764:android:b79ca03160da5708e18a71',
    messagingSenderId: '350442385764',
    projectId: 'flutter-project-una',
    storageBucket: 'flutter-project-una.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpYm04790XO5KiFEl-_ZoTb1qZrlPetc',
    appId: '1:350442385764:ios:0e9d5a19473770c3e18a71',
    messagingSenderId: '350442385764',
    projectId: 'flutter-project-una',
    storageBucket: 'flutter-project-una.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
